const constants = {
  ADD_COMP_NAME: "ADD_COMP_NAME",
  CHANGE_STYLE : "CHANGE_STYLE",
  ADD_COMPONENTS: "ADD_COMPONENTS",
  CHANGE_SINGLE_VIEW: "CHANGE_SINGLE_VIEW",
  CHANGE_LIST_VIEW: "CHANGE_LIST_VIEW"
}

export default constants
