const constants = {
  ADD_COMP_NAME: "ADD_COMP_NAME",
  ADD_ITEM_PATH: "ADD_ITEM_PATH",
  CHANGE_SINGLE_VIEW: "CHANGE_SINGLE_VIEW",
  CHANGE_LIST_VIEW: "CHANGE_LIST_VIEW",
  SET_AEM_STYLES: "SET_AEM_STYLES",
  SET_AEM_RESPONSE: "SET_AEM_RESPONSE",
  SHOW_LOADING: "SHOW_LOADING",
  LOG_AS_DESIGNER: "LOG_AS_DESIGNER"
}

export default constants
